export const images = {
  Frame3: 'https://Camber62.github.io/react-tilda-app/images/Frame3.png',
  Frame4: 'https://Camber62.github.io/react-tilda-app/images/Frame4.png',
  Group12: 'https://Camber62.github.io/react-tilda-app/images/Group12.png',
  Group9: 'https://Camber62.github.io/react-tilda-app/images/Group9.png',
  Group10: 'https://Camber62.github.io/react-tilda-app/images/Group10.png',
  Group11: 'https://Camber62.github.io/react-tilda-app/images/Group11.png',
  Group8: 'https://Camber62.github.io/react-tilda-app/images/Group8.png',
  Group13: 'https://Camber62.github.io/react-tilda-app/images/Group13.png',
  Group67: 'https://Camber62.github.io/react-tilda-app/images/Group67.png',
  Group66: 'https://Camber62.github.io/react-tilda-app/images/Group66.png',
  Vector: 'https://Camber62.github.io/react-tilda-app/images/Vector.png',
  Ok: 'https://Camber62.github.io/react-tilda-app/images/Ok.png',
  Close: 'https://Camber62.github.io/react-tilda-app/images/Close.png',
  CloseBg: 'https://Camber62.github.io/react-tilda-app/images/CloseBg.png',
  History: 'https://Camber62.github.io/react-tilda-app/images/History.png',
  Vector6: 'https://Camber62.github.io/react-tilda-app/images/Vector6.png',
  Back: 'https://Camber62.github.io/react-tilda-app/images/Back.png',
  Send: 'https://Camber62.github.io/react-tilda-app/images/Send.png',
}; 